[nixpacks]
node_version = "16.20.2"

[[nixpacks.packages]]
name = "gcc"
type = "runtime"

[[nixpacks.packages]]
name = "make"
type = "runtime"

[[nixpacks.packages]]
name = "python3"
type = "runtime"
